language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://bethtest-3.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "D1xLN1RzACWmznb6sT1sq1WGpA8RF99bm8j2nQD96oDmkJq3R3i0epYTrOHewvsOG1XT9BeBa9K2eabkQmCvOQSaO3IbK6bLS3Oo+AP656XQl3RqQmFW+cQw5LmOB2Nte7FU6HQdrubNPentiO6MevQqALsn0ptvdN7FxhtkEDwJMD0deLMdOBFA09ytTae7g8cpC2jW6/wLhmmQzJr6uy435YcNahJzlTagHXWLQdSbhEc7ct5KCrWSqgoGPIVDFkJCwy5hxJMCG5vYOF7h8Bm7BoGWyb3RNjZmi8Cf7qRJKQIQQd3OmtfUuSTj0p3xNcsxSreIB4yl1pWTUs5GNl3L6/hIN2It7VMBkSRUlFV4cLb+ZcbKSWjD2mUPr4nvoLNyauA5pIyweMiHLGaEoxVNZCoFtkwl6OoK9hemvnT3p8Hi4Bx/nz1mouOUhok4NsSn4YClpdvW5xsOiIIybgpzDp/DAvzCxbfDoVEcnl6wb73OMoqfyAi9R2ot9hnVOLjX/CwU9JgyduuzFnS+XQ4zbEzQqqMhAsbW05XQLRIJw0EVTwEXpJEEYNF683CIaTHpLtZllHZEeJhUzANQB854UQFrl3cW30YIP/hLfpq9QN97amDLtCrdTYtpWLYeg48gGI44fNLE32cSS8o5JYpBSERzkpXfI5B+1lyV/oA="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
